appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Gz62Z6npB1/MLjsHe7Juc362+fvIjAkCsC/bgd8ouw7JYgNLwVlXP+0hjl7E4Hq4kxoSduAC6gytIwOMu6kwF53eD6gOBuBJMQ/lnLekoWm4at2Q/FAzKvnA0a9CTZzZgxmmGGL55OIWTpv2B+7CEQMEETcAfYQ/1n/4eUAjnjs4BgZo7usM1nD8yyu0lqD5rwUlTocihMXJ6qBMbLPKaH6beoforSJwu3Tuiq5w+NATfU3jaYhhOGEBt5PjMOQnIgPX5D1+dRnSa8M3jRnSDR/lsuO6BmcuQ0yZKPe+ovoSBXh8Tkra8PAe/ojqRX0hbJEOXNIS/8vS8HO0r6zrucMlEne4kuX9XqRrI31UrgnkOBtaX9nJoMlpKmqKjm01F3qApPslUb8qzMOSjQ0rDEvM26OL/ULlHxVb6i3kSBMF0NcGRgu8nITEtJ7u3xEVcLirRGRRDWImyNt8bfazuqIHvOaqChP7P7JP6owGbdoQr3XoovEBaeBNJ/BuGLG1eFXoR8rv5OseVSn2OU7j70HixktJstp7FRVcdKvgmgFPOkY+c+2yERu3+v5MrYpTF3BefaUGrgsIGxVlzjrtBlBL+TMNS/YH1Ytu1NoGNsZNQXQ3UB2M0uy2H6grgHRI3ee3QkP8wmjU8t0MZGQ1DPjGo6PTSA+tQ7uICqWe6Ew=
